/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChannelManagerRouteImport } from './routes/channel-manager'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as CheckOutRouteImport } from './routes/check-out'
import { Route as EzDashboardRouteImport } from './routes/ez-dashboard'
import { Route as FoliosRouteImport } from './routes/folios'
import { Route as FrontDeskRouteImport } from './routes/front-desk'
import { Route as HousekeepingRouteImport } from './routes/housekeeping'
import { Route as PosRouteImport } from './routes/pos'
import { Route as BanquetIdRouteImport } from './routes/banquet.$id'
import { Route as BanquetEventsRouteImport } from './routes/banquet.events'
import { Route as BanquetNewRouteImport } from './routes/banquet.new'
import { Route as CrmFeedbackRouteImport } from './routes/crm.feedback'
import { Route as FinanceLedgerRouteImport } from './routes/finance.ledger'
import { Route as GuestsIndexRouteImport } from './routes/guests.index'
import { Route as GuestsIdRouteImport } from './routes/guests.$id'
import { Route as GuestsNewRouteImport } from './routes/guests.new'
import { Route as HrNewRouteImport } from './routes/hr.new'
import { Route as HrStaffRouteImport } from './routes/hr.staff'
import { Route as LaundryNewRouteImport } from './routes/laundry.new'
import { Route as LaundryOrdersRouteImport } from './routes/laundry.orders'
import { Route as ReportsAuditRouteImport } from './routes/reports.audit'
import { Route as ReportsOccupancyRouteImport } from './routes/reports.occupancy'
import { Route as ReportsRevenueRouteImport } from './routes/reports.revenue'
import { Route as ReservationsIndexRouteImport } from './routes/reservations.index'
import { Route as ReservationsIdRouteImport } from './routes/reservations.$id'
import { Route as ReservationsCalendarRouteImport } from './routes/reservations.calendar'
import { Route as ReservationsNewRouteImport } from './routes/reservations.new'
import { Route as RestaurantBillingRouteImport } from './routes/restaurant.billing'
import { Route as RestaurantKdsRouteImport } from './routes/restaurant.kds'
import { Route as RestaurantMenuRouteImport } from './routes/restaurant.menu'
import { Route as RestaurantOrdersRouteImport } from './routes/restaurant.orders'
import { Route as RestaurantTablesRouteImport } from './routes/restaurant.tables'
import { Route as RoomsGridRouteImport } from './routes/rooms.grid'
import { Route as RoomsListRouteImport } from './routes/rooms.list'
import { Route as RoomsMaintenanceRouteImport } from './routes/rooms.maintenance'
import { Route as SettingsHotelRouteImport } from './routes/settings.hotel'
import { Route as InventoryGrnIndexRouteImport } from './routes/inventory.grn.index'
import { Route as InventoryGrnNewRouteImport } from './routes/inventory.grn.new'
import { Route as InventoryProductsIndexRouteImport } from './routes/inventory.products.index'
import { Route as InventoryProductsNewRouteImport } from './routes/inventory.products.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelManagerRoute = ChannelManagerRouteImport.update({
  id: '/channel-manager',
  path: '/channel-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckOutRoute = CheckOutRouteImport.update({
  id: '/check-out',
  path: '/check-out',
  getParentRoute: () => rootRouteImport,
} as any)
const EzDashboardRoute = EzDashboardRouteImport.update({
  id: '/ez-dashboard',
  path: '/ez-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FoliosRoute = FoliosRouteImport.update({
  id: '/folios',
  path: '/folios',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontDeskRoute = FrontDeskRouteImport.update({
  id: '/front-desk',
  path: '/front-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const HousekeepingRoute = HousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const BanquetIdRoute = BanquetIdRouteImport.update({
  id: '/banquet/$id',
  path: '/banquet/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BanquetEventsRoute = BanquetEventsRouteImport.update({
  id: '/banquet/events',
  path: '/banquet/events',
  getParentRoute: () => rootRouteImport,
} as any)
const BanquetNewRoute = BanquetNewRouteImport.update({
  id: '/banquet/new',
  path: '/banquet/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmFeedbackRoute = CrmFeedbackRouteImport.update({
  id: '/crm/feedback',
  path: '/crm/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceLedgerRoute = FinanceLedgerRouteImport.update({
  id: '/finance/ledger',
  path: '/finance/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsIndexRoute = GuestsIndexRouteImport.update({
  id: '/guests/',
  path: '/guests/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsIdRoute = GuestsIdRouteImport.update({
  id: '/guests/$id',
  path: '/guests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsNewRoute = GuestsNewRouteImport.update({
  id: '/guests/new',
  path: '/guests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HrNewRoute = HrNewRouteImport.update({
  id: '/hr/new',
  path: '/hr/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HrStaffRoute = HrStaffRouteImport.update({
  id: '/hr/staff',
  path: '/hr/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const LaundryNewRoute = LaundryNewRouteImport.update({
  id: '/laundry/new',
  path: '/laundry/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LaundryOrdersRoute = LaundryOrdersRouteImport.update({
  id: '/laundry/orders',
  path: '/laundry/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAuditRoute = ReportsAuditRouteImport.update({
  id: '/reports/audit',
  path: '/reports/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsOccupancyRoute = ReportsOccupancyRouteImport.update({
  id: '/reports/occupancy',
  path: '/reports/occupancy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRevenueRoute = ReportsRevenueRouteImport.update({
  id: '/reports/revenue',
  path: '/reports/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsIndexRoute = ReservationsIndexRouteImport.update({
  id: '/reservations/',
  path: '/reservations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsIdRoute = ReservationsIdRouteImport.update({
  id: '/reservations/$id',
  path: '/reservations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsCalendarRoute = ReservationsCalendarRouteImport.update({
  id: '/reservations/calendar',
  path: '/reservations/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsNewRoute = ReservationsNewRouteImport.update({
  id: '/reservations/new',
  path: '/reservations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantBillingRoute = RestaurantBillingRouteImport.update({
  id: '/restaurant/billing',
  path: '/restaurant/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantKdsRoute = RestaurantKdsRouteImport.update({
  id: '/restaurant/kds',
  path: '/restaurant/kds',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantMenuRoute = RestaurantMenuRouteImport.update({
  id: '/restaurant/menu',
  path: '/restaurant/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantOrdersRoute = RestaurantOrdersRouteImport.update({
  id: '/restaurant/orders',
  path: '/restaurant/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantTablesRoute = RestaurantTablesRouteImport.update({
  id: '/restaurant/tables',
  path: '/restaurant/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsGridRoute = RoomsGridRouteImport.update({
  id: '/rooms/grid',
  path: '/rooms/grid',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsListRoute = RoomsListRouteImport.update({
  id: '/rooms/list',
  path: '/rooms/list',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsMaintenanceRoute = RoomsMaintenanceRouteImport.update({
  id: '/rooms/maintenance',
  path: '/rooms/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHotelRoute = SettingsHotelRouteImport.update({
  id: '/settings/hotel',
  path: '/settings/hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryGrnIndexRoute = InventoryGrnIndexRouteImport.update({
  id: '/inventory/grn/',
  path: '/inventory/grn/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryGrnNewRoute = InventoryGrnNewRouteImport.update({
  id: '/inventory/grn/new',
  path: '/inventory/grn/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryProductsIndexRoute = InventoryProductsIndexRouteImport.update({
  id: '/inventory/products/',
  path: '/inventory/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryProductsNewRoute = InventoryProductsNewRouteImport.update({
  id: '/inventory/products/new',
  path: '/inventory/products/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channel-manager': typeof ChannelManagerRoute
  '/check-in': typeof CheckInRoute
  '/check-out': typeof CheckOutRoute
  '/ez-dashboard': typeof EzDashboardRoute
  '/folios': typeof FoliosRoute
  '/front-desk': typeof FrontDeskRoute
  '/housekeeping': typeof HousekeepingRoute
  '/pos': typeof PosRoute
  '/banquet/$id': typeof BanquetIdRoute
  '/banquet/events': typeof BanquetEventsRoute
  '/banquet/new': typeof BanquetNewRoute
  '/crm/feedback': typeof CrmFeedbackRoute
  '/finance/ledger': typeof FinanceLedgerRoute
  '/guests/$id': typeof GuestsIdRoute
  '/guests/new': typeof GuestsNewRoute
  '/hr/new': typeof HrNewRoute
  '/hr/staff': typeof HrStaffRoute
  '/laundry/new': typeof LaundryNewRoute
  '/laundry/orders': typeof LaundryOrdersRoute
  '/reports/audit': typeof ReportsAuditRoute
  '/reports/occupancy': typeof ReportsOccupancyRoute
  '/reports/revenue': typeof ReportsRevenueRoute
  '/reservations/$id': typeof ReservationsIdRoute
  '/reservations/calendar': typeof ReservationsCalendarRoute
  '/reservations/new': typeof ReservationsNewRoute
  '/restaurant/billing': typeof RestaurantBillingRoute
  '/restaurant/kds': typeof RestaurantKdsRoute
  '/restaurant/menu': typeof RestaurantMenuRoute
  '/restaurant/orders': typeof RestaurantOrdersRoute
  '/restaurant/tables': typeof RestaurantTablesRoute
  '/rooms/grid': typeof RoomsGridRoute
  '/rooms/list': typeof RoomsListRoute
  '/rooms/maintenance': typeof RoomsMaintenanceRoute
  '/settings/hotel': typeof SettingsHotelRoute
  '/guests/': typeof GuestsIndexRoute
  '/reservations/': typeof ReservationsIndexRoute
  '/inventory/grn/new': typeof InventoryGrnNewRoute
  '/inventory/products/new': typeof InventoryProductsNewRoute
  '/inventory/grn/': typeof InventoryGrnIndexRoute
  '/inventory/products/': typeof InventoryProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channel-manager': typeof ChannelManagerRoute
  '/check-in': typeof CheckInRoute
  '/check-out': typeof CheckOutRoute
  '/ez-dashboard': typeof EzDashboardRoute
  '/folios': typeof FoliosRoute
  '/front-desk': typeof FrontDeskRoute
  '/housekeeping': typeof HousekeepingRoute
  '/pos': typeof PosRoute
  '/banquet/$id': typeof BanquetIdRoute
  '/banquet/events': typeof BanquetEventsRoute
  '/banquet/new': typeof BanquetNewRoute
  '/crm/feedback': typeof CrmFeedbackRoute
  '/finance/ledger': typeof FinanceLedgerRoute
  '/guests/$id': typeof GuestsIdRoute
  '/guests/new': typeof GuestsNewRoute
  '/hr/new': typeof HrNewRoute
  '/hr/staff': typeof HrStaffRoute
  '/laundry/new': typeof LaundryNewRoute
  '/laundry/orders': typeof LaundryOrdersRoute
  '/reports/audit': typeof ReportsAuditRoute
  '/reports/occupancy': typeof ReportsOccupancyRoute
  '/reports/revenue': typeof ReportsRevenueRoute
  '/reservations/$id': typeof ReservationsIdRoute
  '/reservations/calendar': typeof ReservationsCalendarRoute
  '/reservations/new': typeof ReservationsNewRoute
  '/restaurant/billing': typeof RestaurantBillingRoute
  '/restaurant/kds': typeof RestaurantKdsRoute
  '/restaurant/menu': typeof RestaurantMenuRoute
  '/restaurant/orders': typeof RestaurantOrdersRoute
  '/restaurant/tables': typeof RestaurantTablesRoute
  '/rooms/grid': typeof RoomsGridRoute
  '/rooms/list': typeof RoomsListRoute
  '/rooms/maintenance': typeof RoomsMaintenanceRoute
  '/settings/hotel': typeof SettingsHotelRoute
  '/guests': typeof GuestsIndexRoute
  '/reservations': typeof ReservationsIndexRoute
  '/inventory/grn/new': typeof InventoryGrnNewRoute
  '/inventory/products/new': typeof InventoryProductsNewRoute
  '/inventory/grn': typeof InventoryGrnIndexRoute
  '/inventory/products': typeof InventoryProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channel-manager': typeof ChannelManagerRoute
  '/check-in': typeof CheckInRoute
  '/check-out': typeof CheckOutRoute
  '/ez-dashboard': typeof EzDashboardRoute
  '/folios': typeof FoliosRoute
  '/front-desk': typeof FrontDeskRoute
  '/housekeeping': typeof HousekeepingRoute
  '/pos': typeof PosRoute
  '/banquet/$id': typeof BanquetIdRoute
  '/banquet/events': typeof BanquetEventsRoute
  '/banquet/new': typeof BanquetNewRoute
  '/crm/feedback': typeof CrmFeedbackRoute
  '/finance/ledger': typeof FinanceLedgerRoute
  '/guests/$id': typeof GuestsIdRoute
  '/guests/new': typeof GuestsNewRoute
  '/hr/new': typeof HrNewRoute
  '/hr/staff': typeof HrStaffRoute
  '/laundry/new': typeof LaundryNewRoute
  '/laundry/orders': typeof LaundryOrdersRoute
  '/reports/audit': typeof ReportsAuditRoute
  '/reports/occupancy': typeof ReportsOccupancyRoute
  '/reports/revenue': typeof ReportsRevenueRoute
  '/reservations/$id': typeof ReservationsIdRoute
  '/reservations/calendar': typeof ReservationsCalendarRoute
  '/reservations/new': typeof ReservationsNewRoute
  '/restaurant/billing': typeof RestaurantBillingRoute
  '/restaurant/kds': typeof RestaurantKdsRoute
  '/restaurant/menu': typeof RestaurantMenuRoute
  '/restaurant/orders': typeof RestaurantOrdersRoute
  '/restaurant/tables': typeof RestaurantTablesRoute
  '/rooms/grid': typeof RoomsGridRoute
  '/rooms/list': typeof RoomsListRoute
  '/rooms/maintenance': typeof RoomsMaintenanceRoute
  '/settings/hotel': typeof SettingsHotelRoute
  '/guests/': typeof GuestsIndexRoute
  '/reservations/': typeof ReservationsIndexRoute
  '/inventory/grn/new': typeof InventoryGrnNewRoute
  '/inventory/products/new': typeof InventoryProductsNewRoute
  '/inventory/grn/': typeof InventoryGrnIndexRoute
  '/inventory/products/': typeof InventoryProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channel-manager'
    | '/check-in'
    | '/check-out'
    | '/ez-dashboard'
    | '/folios'
    | '/front-desk'
    | '/housekeeping'
    | '/pos'
    | '/banquet/$id'
    | '/banquet/events'
    | '/banquet/new'
    | '/crm/feedback'
    | '/finance/ledger'
    | '/guests/$id'
    | '/guests/new'
    | '/hr/new'
    | '/hr/staff'
    | '/laundry/new'
    | '/laundry/orders'
    | '/reports/audit'
    | '/reports/occupancy'
    | '/reports/revenue'
    | '/reservations/$id'
    | '/reservations/calendar'
    | '/reservations/new'
    | '/restaurant/billing'
    | '/restaurant/kds'
    | '/restaurant/menu'
    | '/restaurant/orders'
    | '/restaurant/tables'
    | '/rooms/grid'
    | '/rooms/list'
    | '/rooms/maintenance'
    | '/settings/hotel'
    | '/guests/'
    | '/reservations/'
    | '/inventory/grn/new'
    | '/inventory/products/new'
    | '/inventory/grn/'
    | '/inventory/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channel-manager'
    | '/check-in'
    | '/check-out'
    | '/ez-dashboard'
    | '/folios'
    | '/front-desk'
    | '/housekeeping'
    | '/pos'
    | '/banquet/$id'
    | '/banquet/events'
    | '/banquet/new'
    | '/crm/feedback'
    | '/finance/ledger'
    | '/guests/$id'
    | '/guests/new'
    | '/hr/new'
    | '/hr/staff'
    | '/laundry/new'
    | '/laundry/orders'
    | '/reports/audit'
    | '/reports/occupancy'
    | '/reports/revenue'
    | '/reservations/$id'
    | '/reservations/calendar'
    | '/reservations/new'
    | '/restaurant/billing'
    | '/restaurant/kds'
    | '/restaurant/menu'
    | '/restaurant/orders'
    | '/restaurant/tables'
    | '/rooms/grid'
    | '/rooms/list'
    | '/rooms/maintenance'
    | '/settings/hotel'
    | '/guests'
    | '/reservations'
    | '/inventory/grn/new'
    | '/inventory/products/new'
    | '/inventory/grn'
    | '/inventory/products'
  id:
    | '__root__'
    | '/'
    | '/channel-manager'
    | '/check-in'
    | '/check-out'
    | '/ez-dashboard'
    | '/folios'
    | '/front-desk'
    | '/housekeeping'
    | '/pos'
    | '/banquet/$id'
    | '/banquet/events'
    | '/banquet/new'
    | '/crm/feedback'
    | '/finance/ledger'
    | '/guests/$id'
    | '/guests/new'
    | '/hr/new'
    | '/hr/staff'
    | '/laundry/new'
    | '/laundry/orders'
    | '/reports/audit'
    | '/reports/occupancy'
    | '/reports/revenue'
    | '/reservations/$id'
    | '/reservations/calendar'
    | '/reservations/new'
    | '/restaurant/billing'
    | '/restaurant/kds'
    | '/restaurant/menu'
    | '/restaurant/orders'
    | '/restaurant/tables'
    | '/rooms/grid'
    | '/rooms/list'
    | '/rooms/maintenance'
    | '/settings/hotel'
    | '/guests/'
    | '/reservations/'
    | '/inventory/grn/new'
    | '/inventory/products/new'
    | '/inventory/grn/'
    | '/inventory/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelManagerRoute: typeof ChannelManagerRoute
  CheckInRoute: typeof CheckInRoute
  CheckOutRoute: typeof CheckOutRoute
  EzDashboardRoute: typeof EzDashboardRoute
  FoliosRoute: typeof FoliosRoute
  FrontDeskRoute: typeof FrontDeskRoute
  HousekeepingRoute: typeof HousekeepingRoute
  PosRoute: typeof PosRoute
  BanquetIdRoute: typeof BanquetIdRoute
  BanquetEventsRoute: typeof BanquetEventsRoute
  BanquetNewRoute: typeof BanquetNewRoute
  CrmFeedbackRoute: typeof CrmFeedbackRoute
  FinanceLedgerRoute: typeof FinanceLedgerRoute
  GuestsIdRoute: typeof GuestsIdRoute
  GuestsNewRoute: typeof GuestsNewRoute
  HrNewRoute: typeof HrNewRoute
  HrStaffRoute: typeof HrStaffRoute
  LaundryNewRoute: typeof LaundryNewRoute
  LaundryOrdersRoute: typeof LaundryOrdersRoute
  ReportsAuditRoute: typeof ReportsAuditRoute
  ReportsOccupancyRoute: typeof ReportsOccupancyRoute
  ReportsRevenueRoute: typeof ReportsRevenueRoute
  ReservationsIdRoute: typeof ReservationsIdRoute
  ReservationsCalendarRoute: typeof ReservationsCalendarRoute
  ReservationsNewRoute: typeof ReservationsNewRoute
  RestaurantBillingRoute: typeof RestaurantBillingRoute
  RestaurantKdsRoute: typeof RestaurantKdsRoute
  RestaurantMenuRoute: typeof RestaurantMenuRoute
  RestaurantOrdersRoute: typeof RestaurantOrdersRoute
  RestaurantTablesRoute: typeof RestaurantTablesRoute
  RoomsGridRoute: typeof RoomsGridRoute
  RoomsListRoute: typeof RoomsListRoute
  RoomsMaintenanceRoute: typeof RoomsMaintenanceRoute
  SettingsHotelRoute: typeof SettingsHotelRoute
  GuestsIndexRoute: typeof GuestsIndexRoute
  ReservationsIndexRoute: typeof ReservationsIndexRoute
  InventoryGrnNewRoute: typeof InventoryGrnNewRoute
  InventoryProductsNewRoute: typeof InventoryProductsNewRoute
  InventoryGrnIndexRoute: typeof InventoryGrnIndexRoute
  InventoryProductsIndexRoute: typeof InventoryProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel-manager': {
      id: '/channel-manager'
      path: '/channel-manager'
      fullPath: '/channel-manager'
      preLoaderRoute: typeof ChannelManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-out': {
      id: '/check-out'
      path: '/check-out'
      fullPath: '/check-out'
      preLoaderRoute: typeof CheckOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ez-dashboard': {
      id: '/ez-dashboard'
      path: '/ez-dashboard'
      fullPath: '/ez-dashboard'
      preLoaderRoute: typeof EzDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folios': {
      id: '/folios'
      path: '/folios'
      fullPath: '/folios'
      preLoaderRoute: typeof FoliosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/front-desk': {
      id: '/front-desk'
      path: '/front-desk'
      fullPath: '/front-desk'
      preLoaderRoute: typeof FrontDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housekeeping': {
      id: '/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof HousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banquet/$id': {
      id: '/banquet/$id'
      path: '/banquet/$id'
      fullPath: '/banquet/$id'
      preLoaderRoute: typeof BanquetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banquet/events': {
      id: '/banquet/events'
      path: '/banquet/events'
      fullPath: '/banquet/events'
      preLoaderRoute: typeof BanquetEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banquet/new': {
      id: '/banquet/new'
      path: '/banquet/new'
      fullPath: '/banquet/new'
      preLoaderRoute: typeof BanquetNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/feedback': {
      id: '/crm/feedback'
      path: '/crm/feedback'
      fullPath: '/crm/feedback'
      preLoaderRoute: typeof CrmFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/ledger': {
      id: '/finance/ledger'
      path: '/finance/ledger'
      fullPath: '/finance/ledger'
      preLoaderRoute: typeof FinanceLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guests/': {
      id: '/guests/'
      path: '/guests'
      fullPath: '/guests/'
      preLoaderRoute: typeof GuestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guests/$id': {
      id: '/guests/$id'
      path: '/guests/$id'
      fullPath: '/guests/$id'
      preLoaderRoute: typeof GuestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guests/new': {
      id: '/guests/new'
      path: '/guests/new'
      fullPath: '/guests/new'
      preLoaderRoute: typeof GuestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/new': {
      id: '/hr/new'
      path: '/hr/new'
      fullPath: '/hr/new'
      preLoaderRoute: typeof HrNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/staff': {
      id: '/hr/staff'
      path: '/hr/staff'
      fullPath: '/hr/staff'
      preLoaderRoute: typeof HrStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laundry/new': {
      id: '/laundry/new'
      path: '/laundry/new'
      fullPath: '/laundry/new'
      preLoaderRoute: typeof LaundryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laundry/orders': {
      id: '/laundry/orders'
      path: '/laundry/orders'
      fullPath: '/laundry/orders'
      preLoaderRoute: typeof LaundryOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/audit': {
      id: '/reports/audit'
      path: '/reports/audit'
      fullPath: '/reports/audit'
      preLoaderRoute: typeof ReportsAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/occupancy': {
      id: '/reports/occupancy'
      path: '/reports/occupancy'
      fullPath: '/reports/occupancy'
      preLoaderRoute: typeof ReportsOccupancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/revenue': {
      id: '/reports/revenue'
      path: '/reports/revenue'
      fullPath: '/reports/revenue'
      preLoaderRoute: typeof ReportsRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/': {
      id: '/reservations/'
      path: '/reservations'
      fullPath: '/reservations/'
      preLoaderRoute: typeof ReservationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/$id': {
      id: '/reservations/$id'
      path: '/reservations/$id'
      fullPath: '/reservations/$id'
      preLoaderRoute: typeof ReservationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/calendar': {
      id: '/reservations/calendar'
      path: '/reservations/calendar'
      fullPath: '/reservations/calendar'
      preLoaderRoute: typeof ReservationsCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/new': {
      id: '/reservations/new'
      path: '/reservations/new'
      fullPath: '/reservations/new'
      preLoaderRoute: typeof ReservationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/billing': {
      id: '/restaurant/billing'
      path: '/restaurant/billing'
      fullPath: '/restaurant/billing'
      preLoaderRoute: typeof RestaurantBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/kds': {
      id: '/restaurant/kds'
      path: '/restaurant/kds'
      fullPath: '/restaurant/kds'
      preLoaderRoute: typeof RestaurantKdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/menu': {
      id: '/restaurant/menu'
      path: '/restaurant/menu'
      fullPath: '/restaurant/menu'
      preLoaderRoute: typeof RestaurantMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/orders': {
      id: '/restaurant/orders'
      path: '/restaurant/orders'
      fullPath: '/restaurant/orders'
      preLoaderRoute: typeof RestaurantOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/tables': {
      id: '/restaurant/tables'
      path: '/restaurant/tables'
      fullPath: '/restaurant/tables'
      preLoaderRoute: typeof RestaurantTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/grid': {
      id: '/rooms/grid'
      path: '/rooms/grid'
      fullPath: '/rooms/grid'
      preLoaderRoute: typeof RoomsGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/list': {
      id: '/rooms/list'
      path: '/rooms/list'
      fullPath: '/rooms/list'
      preLoaderRoute: typeof RoomsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/maintenance': {
      id: '/rooms/maintenance'
      path: '/rooms/maintenance'
      fullPath: '/rooms/maintenance'
      preLoaderRoute: typeof RoomsMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/hotel': {
      id: '/settings/hotel'
      path: '/settings/hotel'
      fullPath: '/settings/hotel'
      preLoaderRoute: typeof SettingsHotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/grn/': {
      id: '/inventory/grn/'
      path: '/inventory/grn'
      fullPath: '/inventory/grn/'
      preLoaderRoute: typeof InventoryGrnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/grn/new': {
      id: '/inventory/grn/new'
      path: '/inventory/grn/new'
      fullPath: '/inventory/grn/new'
      preLoaderRoute: typeof InventoryGrnNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/products/': {
      id: '/inventory/products/'
      path: '/inventory/products'
      fullPath: '/inventory/products/'
      preLoaderRoute: typeof InventoryProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/products/new': {
      id: '/inventory/products/new'
      path: '/inventory/products/new'
      fullPath: '/inventory/products/new'
      preLoaderRoute: typeof InventoryProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelManagerRoute: ChannelManagerRoute,
  CheckInRoute: CheckInRoute,
  CheckOutRoute: CheckOutRoute,
  EzDashboardRoute: EzDashboardRoute,
  FoliosRoute: FoliosRoute,
  FrontDeskRoute: FrontDeskRoute,
  HousekeepingRoute: HousekeepingRoute,
  PosRoute: PosRoute,
  BanquetIdRoute: BanquetIdRoute,
  BanquetEventsRoute: BanquetEventsRoute,
  BanquetNewRoute: BanquetNewRoute,
  CrmFeedbackRoute: CrmFeedbackRoute,
  FinanceLedgerRoute: FinanceLedgerRoute,
  GuestsIdRoute: GuestsIdRoute,
  GuestsNewRoute: GuestsNewRoute,
  HrNewRoute: HrNewRoute,
  HrStaffRoute: HrStaffRoute,
  LaundryNewRoute: LaundryNewRoute,
  LaundryOrdersRoute: LaundryOrdersRoute,
  ReportsAuditRoute: ReportsAuditRoute,
  ReportsOccupancyRoute: ReportsOccupancyRoute,
  ReportsRevenueRoute: ReportsRevenueRoute,
  ReservationsIdRoute: ReservationsIdRoute,
  ReservationsCalendarRoute: ReservationsCalendarRoute,
  ReservationsNewRoute: ReservationsNewRoute,
  RestaurantBillingRoute: RestaurantBillingRoute,
  RestaurantKdsRoute: RestaurantKdsRoute,
  RestaurantMenuRoute: RestaurantMenuRoute,
  RestaurantOrdersRoute: RestaurantOrdersRoute,
  RestaurantTablesRoute: RestaurantTablesRoute,
  RoomsGridRoute: RoomsGridRoute,
  RoomsListRoute: RoomsListRoute,
  RoomsMaintenanceRoute: RoomsMaintenanceRoute,
  SettingsHotelRoute: SettingsHotelRoute,
  GuestsIndexRoute: GuestsIndexRoute,
  ReservationsIndexRoute: ReservationsIndexRoute,
  InventoryGrnNewRoute: InventoryGrnNewRoute,
  InventoryProductsNewRoute: InventoryProductsNewRoute,
  InventoryGrnIndexRoute: InventoryGrnIndexRoute,
  InventoryProductsIndexRoute: InventoryProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
